name: purchases
description: Revenuecat purchases cross platform
version: 0.0.2
homepage: https://github.com/jamesblasco/purchases

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  purchases_flutter: ^3.2.1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 